### ISSUE TITLE
Do you have the codes that labels are not added

### ISSUE THREAD

**Issue by amen183** [chennnnnyize/Renewables_Scenario_Gen_GAN#1]
I have read your codes and it's well written. However, I found that there were no codes that matching the un-supervised learning. Could you upload that one?

**Comment by chennnnnyize** [comment]
Sure, that's a very good suggestion. I will upload the code shortly in this week. Another quick solution is that since in unsupervised case, label doesn't provide any information, you could directly feed a random label (e.g., same uniform distribution as z input) to implement unsupervised generation. Thanks!

**Comment by amen183** [comment]
Did you upload the codes？ I can not find them in your home page. And I have tried the method you told, however the results are not as good as them in paper.
